737:0Traceback (most recent call last):
Failure: twisted.internet.defer.FirstError: FirstError[#0, [Failure instance: Traceback: <type 'exceptions.NameError'>: global name 'str1' is not defined
/home/buildbot/sbox/local/lib/python2.7/site-packages/twisted/internet/defer.py:304:addCallback
/home/buildbot/sbox/local/lib/python2.7/site-packages/twisted/internet/defer.py:293:addCallbacks
/home/buildbot/sbox/local/lib/python2.7/site-packages/twisted/internet/defer.py:575:_runCallbacks
/home/buildbot/buildbot/master/buildbot/process/buildstep.py:583:_startStep_2
--- <exception caught here> ---
/home/buildbot/sbox/local/lib/python2.7/site-packages/twisted/internet/defer.py:137:maybeDeferred
/home/buildbot/master/master.cfg:77:steptest
]]
,